### ISSUE TITLE
SASS Files

### ISSUE THREAD

**Issue by jrobida999** [Advsol/Roanoke_Responsive#2]
Would you be willing to make the SASS files that correspond with this theme available? I'm particularly interested because it would make re-theming out-of-the-box sites for cloud clients MUCH easier.

Thanks,
Jake

**Comment by RoboAndie** [comment]
Hi Jake, thanks for asking. We are working on finding a way to push our Sass code to GitHub that also plays nicely with our current source control. I'll let you know when this becomes available.

Thanks,
Andrea

**Comment by jrobida999** [comment]
Hey Andrea,

I appreciate the response and would be very interested in that. I just recently learned that the SASS files for the themes that ship with iMIS are already included in the shipped product as well --- with the standard rules of course (use copies instead of modifying originals, create backups, support is very limited, etc.)

Are there any plans to start shipping Roanoke with iMIS alongside the other themes?

Thanks,
Jake

**Comment by RoboAndie** [comment]
At this time there are no plans to ship Roanoke with the product, since it's really only intended for developer use and would be confusing to other users. We can certainly think about it though!

Thanks,
Andrea

**Comment by jrobida999** [comment]
Sounds good. Thanks for the update.

Jake
